### Numpy ndarray 개요

- 배열 연산을 위한 패키지
- C/C++ 기반으로 제작되어 연산속도가 빠르다.
- 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 한다.
- 텐서플로우에서는 Numpy와 호환되어 사용됨
- 사용시 별도로 모듈을 임포트 해야됨
- Numpy의 데이터 타입은 ndarray임
- 다차원 배열을 생성 및 연산 가능

In [1]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


[![](https://taewanmerepo.github.io/2018/01/numpy/nparr.jpg)](https://taewanmerepo.github.io/2018/01/numpy/nparr.jpg)

In [5]:
# ndarray.ndim 함수
print('array1: {:0}차원, array2 {:1}차원, array3 {:3}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2 2차원, array3   2차원


In [7]:
# 배열의 생성
# 서로 다른 타입을 가질 수 있는 리스트와 달리 ndarray의
# 데이터 타입은 연산 특성상 같은 데이터만 가능
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [8]:
# 데이터 유형이 다르다면 
# 데이터의 크기가 더 큰 데이터 타입으로 일괄적으로 형 변환을 한다.
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)   # 문자열 U21은 유니코드21을 의미

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [9]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')   # float64로 변환
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')    # int32로 변환
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')   # int32로 변환
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

- arange : 파이썬 기본 내장함수인 range와 같다.
- zeros : 튜플 형태로 shape 값을 전달하면 해당 크기만큼 0으로 채워진 ndarray를 반환.
- ones : 튜플 형태로 shape 값을 전달하면 해당 크기만큼 1으로 채워진 ndarray를 반환.

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)   # arange의 경우 1차원으로 만듦

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

- 차원의 크기를 변경하는 함수

In [12]:
array1 = np.arange(10)
print('array1 : \n', array1)

array2 = array1.reshape(2,5)
print('array2 : \n', array2)

array3 = array1.reshape(5,2)
print('array3 : \n', array3)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array1.reshape(4,3)   # 사이즈가 맞지 않음

ValueError: ignored

In [14]:
# '-1'인자 : 원본 ndarray가 어떤 형태던 상관없이 2차원으로 변경
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)   # 자동으로 2차원으로 만들어줌
print('array2 shape', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape (2, 5)
array3 shape (5, 2)


In [15]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)   # '-1'도 만능이 아님, 사이즈가 맞아야 함

ValueError: ignored

In [17]:
# 배열을 리스트로 바꾸고 싶다면

array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d: \n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5: \n', array5.tolist())
print('array5 shape', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6: \n', array6.tolist())
print('array6 shape', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


indexing

- 단일값 추출

[![](https://qph.cf2.quoracdn.net/main-qimg-7ba562095c4de01a64d7b6ecdd58a2ba)](https://qph.cf2.quoracdn.net/main-qimg-7ba562095c4de01a64d7b6ecdd58a2ba)

In [18]:
# 1에서 부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1 :', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value :', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int64'>


In [21]:
print('맨 뒤의 값 :', array1[-1], ', 맨 뒤에서 두 번째 값 :', array1[-2])

맨 뒤의 값 : 9 , 맨 뒤에서 두 번째 값 : 8


2차원 array에서 인덱싱

[![](https://iq.opengenus.org/content/images/2020/04/index.png)](https://iq.opengenus.org/content/images/2020/04/index.png)

In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값 :', array2d[0,0])
print('(row=0, col=1) index 가리키는 값 :', array2d[0,1])
print('(row=1, col=0) index 가리키는 값 :', array2d[1,0])
print('(row=2, col=2) index 가리키는 값 :', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 : 1
(row=0, col=1) index 가리키는 값 : 2
(row=1, col=0) index 가리키는 값 : 4
(row=2, col=2) index 가리키는 값 : 9


- slicing

In [23]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 다차원 슬라이싱

In [26]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


- fancy indexing

In [27]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print(' array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
 array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


- Boolean indexing

  - 인덱싱 한 곳의 True 값만 반환

In [28]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [29]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [30]:
array1d[[False, False, False, False, False,  True,  True,  True,  True]]

array([6, 7, 8, 9])

### 행렬의 정렬 - sort()와 argsort()

- 행렬 정렬

In [31]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬 :', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np.sort() 호출 후 원본 행렬', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)

원본 행렬 : [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
np.sort() 호출 후 원본 행렬 [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬 : None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [32]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


In [33]:
array2d = np.array([[8,12],
                    [7,11]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('row 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column 방향으로 정렬 : \n', sort_array2d_axis1)

row 방향으로 정렬 : 
 [[ 7 11]
 [ 8 12]]
column 방향으로 정렬 : 
 [[ 8 12]
 [ 7 11]]


- 정렬 행열의 인덱스 반환

In [34]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 :', sort_indices)    # 정렬의 순서를 반환

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

- 행렬 내적

In [37]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)

print('행렬 내적 결과 : \n', dot_product)

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


In [38]:
A = np.array([[1, 2],
              [3, 4]])

transpose_mat = np.transpose(A)   # 행과 열을 바꿈

print('A의 전치 행렬 : \n', transpose_mat)

A의 전치 행렬 : 
 [[1 3]
 [2 4]]
