### 데이터 인코딩

<br>

[참고하면 좋은 글](https://jaeworld.github.io/data%20science/data_encoding/)

<br>

- 레이블 인코딩(Label encoding)

[![](https://blog.kakaocdn.net/dn/bq4BHc/btqInrO6SRM/gnYIpT5tF2WvBeIK30XsT1/img.png)](https://jaeworld.github.io/data%20science/data_encoding/)  

<br>

레이블 인코딩은 숫자형 데이터일 때 진행한다.

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 label 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 :', labels)

인코딩 변환값 : [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스 :', encoder.classes_)

인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [4]:
print('디코딩 원본 값 :', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값 : ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


- 원-핫 인코딩(One-Hot encoding)

[![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FQUtCQ%2FbtqIqYyOJMv%2FJQuQzB7RSFFnCGa0ktA271%2Fimg.png)](https://jaeworld.github.io/data%20science/data_encoding/)  

<br>

원-핫 인코딩은 특성이 범주형을 가질 때 진행한다.  

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [6]:
labels.shape

(8,)

In [7]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [9]:
# 2차원 데이터로 변환합니다
labels = labels.reshape(-1, 1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [11]:
import pandas as pd

df = pd.DataFrame({'item': ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

In [12]:
df.head()

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기

In [13]:
pd.get_dummies(df)    # 원-핫 인코딩을 더미변수라고도 함

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링과 정규화

[참고하면 좋은 글1](https://jaeworld.github.io/data%20science/feature_scaling/)  
[참고하면 좋은 글2](https://glanceyes.tistory.com/79)

<br>

- StandardScaler
- SVM이나 선형회귀, 로지스틱 회귀 모델은 데이터의 분포가 정규분포를 따른다 가정을 했기 때문에 표준화를 통해 데이터의 분포를 정규분포에 맞도록 스케일링 해줘야 한다.  



표준화: 데이터의 피처 각각이 평균이 0이 되고 분산이 1인 가우시안 정규분포를 가진 값으로 변환하는 것.  

[![](https://blog.kakaocdn.net/dn/chYdAb/btqIvDCUIdc/SPkTzOzfNU3RPZtINyS860/img.jpg)](https://jaeworld.github.io/data%20science/feature_scaling/)  

<br>


[![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FQJYiM%2FbtrmEEVGghI%2FwJG5jMKI2LIjb8ivmMQiNk%2Fimg.png)](https://glanceyes.tistory.com/79)



정규화: 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해 주는 개념.  

[![](https://blog.kakaocdn.net/dn/bcKqB7/btqIs8JPkRj/MTGifL23WUzAGKAOndjoVk/img.jpg)](https://jaeworld.github.io/data%20science/feature_scaling/)  

<br>

[![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FTE8Ok%2FbtrmEFtvNW2%2FnqiRbgQp4br2SEVp9w1YhK%2Fimg.png)](https://glanceyes.tistory.com/79)

In [14]:
from sklearn.datasets import load_iris
import pandas as pd
#붓꽃 데이터셋을 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [19]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터셋 변환. fit()과 transform() 활용
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터셋이 numpy ndarray로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


- MinMaxScaler

In [21]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()
#  MinMaxScaler로 데이터셋 변환. fit()과 transform() 활용
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터셋이 numpy ndarray로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature 들의 최댓값')
print(iris_df_scaled.max())


feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature 들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
