In [1]:
# 기본 라이브러리 불러오기
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [2]:
# Breast Cancer 데이터셋 가져오기 (cnfcj: UCI ML Repository)
uci_path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
df = pd.read_csv(uci_path, header=None)
df.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

1. Sample code number            id number
2. Clump Thickness               1 - 10
3. Uniformity of Cell Size       1 - 10
4. Uniformity of Cell Shape      1 - 10
5. Marginal Adhesion             1 - 10
6. Single Epithelial Cell Size   1 - 10
7. Bare Nuclei                   1 - 10
8. Bland Chromatin               1 - 10
9. Normal Nucleoli               1 - 10
10. Mitoses                       1 - 10
11. Class:                        (2 for benign, 4 for malignant)

In [3]:
# 열 이름 지정
df.columns = ['id', 'clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial', 'bare_nuclei', 'chromatin', 'normal_nucleoli', 'mitoses', 'class']

## 2. 데이터 탐색

In [4]:
# 데이터 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   id               699 non-null    int64 
 1   clump            699 non-null    int64 
 2   cell_size        699 non-null    int64 
 3   cell_shape       699 non-null    int64 
 4   adhesion         699 non-null    int64 
 5   epithlial        699 non-null    int64 
 6   bare_nuclei      699 non-null    object
 7   chromatin        699 non-null    int64 
 8   normal_nucleoli  699 non-null    int64 
 9   mitoses          699 non-null    int64 
 10  class            699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [5]:
df.describe()

id       clump   cell_size  cell_shape    adhesion  \
count  6.990000e+02  699.000000  699.000000  699.000000  699.000000   
mean   1.071704e+06    4.417740    3.134478    3.207439    2.806867   
std    6.170957e+05    2.815741    3.051459    2.971913    2.855379   
min    6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.706885e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238298e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        epithlial   chromatin  normal_nucleoli     mitoses       class  
count  699.000000  699.000000       699.000000  699.000000  699.000000  
mean     3.216023    3.437768         2.866953    1.589413    2.689557  
std      2.214300    2.438364         3.053634    1.715078    0.951273  
min      1.000000    1.000000         1.000000    1.000000    2.000000  
25%      2.000000    2.000000         1.000000    1.000000    2.000000  
50%      2.000000    3.000000         1.000000    1.000000    2.000000  
75%      4.000000    5.000000         4.000000    1.000000    4.000000  
max     10.000000   10.000000        10.000000   10.000000    4.000000

In [6]:
df.head()

id  clump  cell_size  cell_shape  adhesion  epithlial bare_nuclei  \
0  1000025      5          1           1         1          2           1   
1  1002945      5          4           4         5          7          10   
2  1015425      3          1           1         1          2           2   
3  1016277      6          8           8         1          3           4   
4  1017023      4          1           1         3          2           1   

   chromatin  normal_nucleoli  mitoses  class  
0          3                1        1      2  
1          3                2        1      2  
2          3                1        1      2  
3          3                7        1      2  
4          3                1        1      2

In [21]:
df['clump'].unique()

array([ 5,  3,  6,  4,  8,  1,  2,  7, 10,  9])

In [9]:
df['cell_size'].unique()

array([ 1,  4,  8, 10,  2,  3,  7,  5,  6,  9])

In [10]:
df['cell_shape'].unique()

array([ 1,  4,  8, 10,  2,  3,  5,  6,  7,  9])

In [11]:
df['adhesion'].unique()

array([ 1,  5,  3,  8, 10,  4,  6,  2,  9,  7])

In [12]:
df['epithlial'].unique()

array([ 2,  7,  3,  1,  6,  4,  5,  8, 10,  9])

In [13]:
df['bare_nuclei'].unique()

array(['1', '10', '2', '4', '3', '9', '7', '?', '5', '8', '6'],
      dtype=object)

In [22]:
df['bare_nuclei'].value_counts()

1     402
10    132
2      30
5      30
3      28
8      21
4      19
?      16
9       9
7       8
6       4
Name: bare_nuclei, dtype: int64

In [14]:
df['chromatin'].unique()

array([ 3,  9,  1,  2,  4,  5,  7,  8,  6, 10])

In [15]:
df['normal_nucleoli'].unique()

array([ 1,  2,  7,  4,  5,  3, 10,  6,  9,  8])

In [16]:
df['mitoses'].unique()

array([ 1,  5,  4,  2,  3,  7, 10,  8,  6])

In [17]:
df['class'].unique()

array([2, 4])

In [26]:
df[df['bare_nuclei'] == '?'].index

Int64Index([23, 40, 139, 145, 158, 164, 235, 249, 275, 292, 294, 297, 315, 321,
            411, 617],
           dtype='int64')

In [27]:
rdf = df.drop(df[df['bare_nuclei'] == '?'].index, axis=0)
rdf.head()

id  clump  cell_size  cell_shape  adhesion  epithlial bare_nuclei  \
0  1000025      5          1           1         1          2           1   
1  1002945      5          4           4         5          7          10   
2  1015425      3          1           1         1          2           2   
3  1016277      6          8           8         1          3           4   
4  1017023      4          1           1         3          2           1   

   chromatin  normal_nucleoli  mitoses  class  
0          3                1        1      2  
1          3                2        1      2  
2          3                1        1      2  
3          3                7        1      2  
4          3                1        1      2

In [28]:
rdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   id               683 non-null    int64 
 1   clump            683 non-null    int64 
 2   cell_size        683 non-null    int64 
 3   cell_shape       683 non-null    int64 
 4   adhesion         683 non-null    int64 
 5   epithlial        683 non-null    int64 
 6   bare_nuclei      683 non-null    object
 7   chromatin        683 non-null    int64 
 8   normal_nucleoli  683 non-null    int64 
 9   mitoses          683 non-null    int64 
 10  class            683 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 64.0+ KB


In [30]:
rdf['bare_nuclei'].unique()

array(['1', '10', '2', '4', '3', '9', '7', '5', '8', '6'], dtype=object)

In [31]:
rdf.describe()

id       clump   cell_size  cell_shape    adhesion  \
count  6.830000e+02  683.000000  683.000000  683.000000  683.000000   
mean   1.076720e+06    4.442167    3.150805    3.215227    2.830161   
std    6.206440e+05    2.820761    3.065145    2.988581    2.864562   
min    6.337500e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.776170e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171795e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238705e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        epithlial   chromatin  normal_nucleoli     mitoses       class  
count  683.000000  683.000000       683.000000  683.000000  683.000000  
mean     3.234261    3.445095         2.869693    1.603221    2.699854  
std      2.223085    2.449697         3.052666    1.732674    0.954592  
min      1.000000    1.000000         1.000000    1.000000    2.000000  
25%      2.000000    2.000000         1.000000    1.000000    2.000000  
50%      2.000000    3.000000         1.000000    1.000000    2.000000  
75%      4.000000    5.000000         4.000000    1.000000    4.000000  
max     10.000000   10.000000        10.000000   10.000000    4.000000

In [32]:
ndf = rdf[['clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial', 'chromatin', 'normal_nucleoli', 'mitoses', 'class']]
ndf.head()

clump  cell_size  cell_shape  adhesion  epithlial  chromatin  \
0      5          1           1         1          2          3   
1      5          4           4         5          7          3   
2      3          1           1         1          2          3   
3      6          8           8         1          3          3   
4      4          1           1         3          2          3   

   normal_nucleoli  mitoses  class  
0                1        1      2  
1                2        1      2  
2                1        1      2  
3                7        1      2  
4                1        1      2

In [33]:
# 속성(변수) 선택
X = ndf[list(ndf.columns)[:-1]]    # 독립 변수 X
y = ndf[list(ndf.columns)[-1]]

In [34]:
X.head()

clump  cell_size  cell_shape  adhesion  epithlial  chromatin  \
0      5          1           1         1          2          3   
1      5          4           4         5          7          3   
2      3          1           1         1          2          3   
3      6          8           8         1          3          3   
4      4          1           1         3          2          3   

   normal_nucleoli  mitoses  
0                1        1  
1                2        1  
2                1        1  
3                7        1  
4                1        1

In [36]:
X.shape

(683, 8)

In [35]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: class, dtype: int64

In [37]:
y.shape

(683,)

In [38]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit(X).transform(X)

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.3,
                                                    random_state=10)

In [40]:
from sklearn.neighbors import KNeighborsClassifier

# 모형 객체 생성(k=5로 설정)
knn = KNeighborsClassifier(n_neighbors=5)

# train data를 가지고 모형 학습
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [41]:
y_hat = knn.predict(X_test)

In [42]:
y_hat.shape

(205,)

In [43]:
y_test.shape

(205,)

In [44]:
import numpy as np
y_test = np.array(y_test)
y_test

array([4, 4, 4, 4, 4, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 2, 4, 2, 4, 2, 2,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 4, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 2, 4, 2, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 4, 2,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2,
       2, 2, 4, 4, 4, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2, 2, 4,
       2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 4,
       2, 4, 4, 4, 2, 4, 2])

In [45]:
import pandas as pd
df = pd.DataFrame({'y_hat': y_hat, 'y': y_test})

In [46]:
df.head()

y_hat  y
0      4  4
1      2  4
2      2  4
3      4  4
4      4  4

In [47]:
df['차이'] = df['y_hat'] == df['y']
df.head()

y_hat  y     차이
0      4  4   True
1      2  4  False
2      2  4  False
3      4  4   True
4      4  4   True

In [48]:
len(df)

205

In [49]:
sum(df['차이'])

193

In [50]:
print('accuracy: ', sum(df['차이']) / len(df))

accuracy:  0.9414634146341463


In [51]:
# 모형 성능 평가 - Confusion Matrix 계산
from sklearn import metrics
knn_matrix = metrics.confusion_matrix(y_test, y_hat)
knn_matrix

array([[128,   3],
       [  9,  65]])

In [52]:
# 모형 성능 평가 - 평가지표 계산
knn_report = metrics.classification_report(y_test, y_hat)
print(knn_report)

              precision    recall  f1-score   support

           2       0.93      0.98      0.96       131
           4       0.96      0.88      0.92        74

    accuracy                           0.94       205
   macro avg       0.95      0.93      0.94       205
weighted avg       0.94      0.94      0.94       205



In [53]:
# 인접한 k개의 sample에 대해 거리와 index를 반환
knn.kneighbors()

(array([[1.48308234, 1.4931896 , 1.69499422, 1.7241772 , 1.74790995],
        [1.35089256, 1.51484997, 1.57910862, 1.61945531, 1.67808285],
        [0.        , 0.35477403, 0.35477403, 0.35477403, 0.35477403],
        ...,
        [0.53752006, 0.63193501, 0.65297591, 0.65297591, 0.65297591],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.80913044, 0.98848113, 1.114703  , 1.12875785, 1.13036115]]),
 array([[149, 173, 102, 369,  12],
        [251,  73, 109, 459,  17],
        [231, 366, 334, 317, 298],
        ...,
        [146, 300, 294, 265,  11],
        [155, 183, 122,  10, 182],
        [ 49, 344, 160, 359, 284]]))